name: Github Action with a cronjob trigger
on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - step1
      # - step 2
      # - step n, use it as the last step
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
